from sklearn.preprocessing import OneHotEncoder
import numpy as np

#add any data you want to test in here/for questions with many options to help save space!!!
first_names = ["John", "Jane", "Michael", "Emily", "David", "Emma", "Daniel", "Olivia", "James", "Sophia"]

major_options = ["Accounting",
        "Actuarial Science",
        "Advertising Major",
        "Aerospace Engineering",
        "African Languages, Literatures, and Linguistics",
        "African Studies",
        "African-American Studies",
        "Agricultural Business and Management",
        "Agricultural Economics",
        "Agricultural Education",
        "Agricultural Journalism",
        "Agricultural Mechanization Major",
        "Agricultural Technology Management",
        "Agricultural/Biological Engineering and Bioengineering",
        "Agriculture",
        "Agronomy and Crop Science",
        "Air Traffic Control",
        "American History",
        "American Literature",
        "American Sign Language",
        "American Studies",
        "Anatomy",
        "Ancient Studies",
        "Animal Behavior and Ethology",
        "Animal Science",
        "Animation and Special Effects",
        "Anthropology",
        "Applied Mathematics",
        "Aquaculture",
        "Aquatic Biology",
        "Arabic",
        "Archeology",
        "Architectural Engineering",
        "Architectural History",
        "Architecture",
        "Art",
        "Art Education",
        "Art History",
        "Art Therapy",
        "Artificial Intelligence and Robotics",
        "Asian-American Studies",
        "Astronomy",
        "Astrophysics",
        "Athletic Training",
        "Atmospheric Science",
        "Automotive Engineering",
        "Aviation",
        "Bakery Science",
        "Biblical Studies",
        "Biochemistry",
        "Bioethics",
        "Biology",
        "Biomedical Engineering",
        "Biomedical Science",
        "Biopsychology",
        "Biotechnology",
        "Botany/Plant Biology",
        "Business Administration/Management",
        "Business Communications",
        "Business Education",
        "Canadian Studies",
        "Caribbean Studies",
        "Cell Biology Major",
        "Ceramic Engineering",
        "Ceramics",
        "Chemical Engineering Major",
        "Chemical Physics",
        "Chemistry Major",
        "Child Care",
        "Child Development",
        "Chinese",
        "Chiropractic",
        "Church Music",
        "Cinematography and Film/Video Production",
        "Circulation Technology",
        "Civil Engineering",
        "Classics",
        "Clinical Psychology",
        "Cognitive Psychology",
        "Communication Disorders",
        "Communications Studies/Speech Communication and Rhetoric",
        "Comparative Literature",
        "Computer and Information Science",
        "Computer Engineering",
        "Computer Graphics",
        "Computer Systems Analysis Major",
        "Construction Management",
        "Counseling",
        "Crafts",
        "Creative Writing",
        "Criminal Science",
        "Criminology",
        "Culinary Arts",
        "Dance",
        "Data Processing",
        "Dental Hygiene",
        "Developmental Psychology",
        "Diagnostic Medical Sonography",
        "Dietetics",
        "Digital Communications and Media/Multimedia",
        "Drawing",
        "Early Childhood Education",
        "East Asian Studies",
        "East European Studies",
        "Ecology",
        "Economics Major",
        "Education",
        "Education Administration",
        "Education of the Deaf",
        "Educational Psychology",
        "Electrical Engineering",
        "Elementary Education",
        "Engineering Mechanics",
        "Engineering Physics",
        "English",
        "English Composition",
        "English Literature Major",
        "Entomology",
        "Entrepreneurship Major",
        "Environmental Design/Architecture",
        "Environmental Science",
        "Environmental/Environmental Health Engineering",
        "Epidemiology",
        "Equine Studies",
        "Ethnic Studies",
        "European History",
        "Experimental Pathology",
        "Experimental Psychology",
        "Fashion Design",
        "Fashion Merchandising",
        "Feed Science",
        "Fiber, Textiles, and Weaving Arts",
        "Film",
        "Finance",
        "Floriculture",
        "Food Science",
        "Forensic Science",
        "Forestry",
        "French",
        "Furniture Design",
        "Game Design",
        "Gay and Lesbian Studies",
        "Genetics",
        "Geography",
        "Geological Engineering",
        "Geology",
        "Geophysics",
        "German",
        "Gerontology",
        "Government Major",
        "Graphic Design",
        "Health Administration",
        "Hebrew",
        "Hispanic-American, Puerto Rican, and Chicano Studies",
        "Historic Preservation",
        "History",
        "Home Economics",
        "Horticulture",
        "Hospitality",
        "Human Development",
        "Human Resources Management Major",
        "Illustration",
        "Industrial Design",
        "Industrial Engineering",
        "Industrial Management",
        "Industrial Psychology",
        "Information Technology",
        "Interior Architecture",
        "Interior Design",
        "International Agriculture",
        "International Business",
        "International Relations",
        "International Studies",
        "Islamic Studies",
        "Italian",
        "Japanese",
        "Jazz Studies",
        "Jewelry and Metalsmithing",
        "Jewish Studies",
        "Journalism",
        "Kinesiology",
        "Korean",
        "Land Use Planning and Management",
        "Landscape Architecture",
        "Landscape Horticulture",
        "Latin American Studies",
        "Library Science",
        "Linguistics",
        "Logistics Management",
        "Management Information Systems",
        "Managerial Economics",
        "Marine Biology Major",
        "Marine Science",
        "Marketing Major",
        "Mass Communication",
        "Massage Therapy",
        "Materials Science",
        "Mathematics",
        "Mechanical Engineering",
        "Medical Technology",
        "Medieval and Renaissance Studies",
        "Mental Health Services",
        "Merchandising and Buying Operations",
        "Metallurgical Engineering",
        "Microbiology",
        "Middle Eastern Studies",
        "Military Science",
        "Mineral Engineering",
        "Missions",
        "Modern Greek",
        "Molecular Biology",
        "Molecular Genetics",
        "Mortuary Science",
        "Museum Studies",
        "Music",
        "Music Education",
        "Music History Major",
        "Music Management",
        "Music Therapy",
        "Musical Theater",
        "Native American Studies",
        "Natural Resources Conservation",
        "Naval Architecture",
        "Neurobiology",
        "Neuroscience",
        "Nuclear Engineering",
        "Nursing Major",
        "Nutrition",
        "Occupational Therapy",
        "Ocean Engineering",
        "Oceanography",
        "Operations Management",
        "Organizational Behavior Studies",
        "Painting",
        "Paleontology",
        "Pastoral Studies",
        "Peace Studies",
        "Petroleum Engineering",
        "Pharmacology",
        "Pharmacy",
        "Philosophy",
        "Photography",
        "Photojournalism Major",
        "Physical Education",
        "Physical Therapy",
        "Physician Assistant",
        "Physics",
        "Physiological Psychology",
        "Piano",
        "Planetary Science",
        "Plant Pathology",
        "Playwriting and Screenwriting",
        "Political Communication",
        "Political Science Major",
        "Portuguese",
        "Pre-Dentistry",
        "Pre-Law",
        "Pre-Medicine",
        "Pre-Optometry",
        "Pre-Seminary",
        "Pre-Veterinary Medicine",
        "Printmaking",
        "Psychology",
        "Public Administration",
        "Public Health",
        "Public Policy Analysis",
        "Public Relations Major",
        "Radio and Television",
        "Radiologic Technology",
        "Range Science and Management",
        "Real Estate",
        "Recording Arts Technology",
        "Recreation Management",
        "Rehabilitation Services",
        "Religious Studies",
        "Respiratory Therapy",
        "Risk Management",
        "Rural Sociology",
        "Russian",
        "Scandinavian Studies",
        "Sculpture",
        "Slavic Languages and Literatures",
        "Social Psychology",
        "Social Work",
        "Sociology",
        "Soil Science",
        "Sound Engineering",
        "South Asian Studies",
        "Southeast Asia Studies",
        "Spanish Major",
        "Special Education",
        "Speech Pathology",
        "Sport and Leisure Studies",
        "Sports Management",
        "Statistics Major",
        "Surveying",
        "Sustainable Resource Management",
        "Teacher Education",
        "Teaching English as a Second Language",
        "Technical Writing",
        "Technology Education",
        "Textile Engineering",
        "Theatre",
        "Theology",
        "Tourism",
        "Toxicology",
        "Turfgrass Science",
        "Urban Planning",
        "Urban Studies",
        "Visual Communication",
        "Voice",
        "Web Design",
        "Webmaster and Web Management",
        "Welding Engineering",
        "Wildlife Management",
        "Women's Studies",
        "Youth Ministries",
        "Zoology" ]

photos = [
        "https://t3.ftcdn.net/jpg/03/67/97/90/360_F_367979072_UdBgmIp2RuFgLsbruOMBVmruR6jCDqfX.jpg",
        "https://www.shutterstock.com/image-photo/confident-handsome-student-holding-books-260nw-366568778.jpg",
        "https://st2.depositphotos.com/1594308/12210/i/950/depositphotos_122104490-stock-photo-smiing-female-college-student.jpg",
        "https://www.shutterstock.com/image-photo/female-college-student-closeup-portrait-260nw-108794702.jpg",
        "https://media.istockphoto.com/id/1351445530/photo/african-student-sitting-in-classroom.jpg?s=612x612&w=0&k=20&c=1ICaZ03iFLzDmxfBkfDkmBGSgj1SDEpsM3eSDgB1KBk=",
        "https://media.gettyimages.com/id/1340766096/photo/beautiful-smiling-female-college-student.jpg?s=612x612&w=gi&k=20&c=WwF5_siESAA9e2y6qo4Z9vbfG8yypA_MnrWg1eOIt_s=",
        "https://t4.ftcdn.net/jpg/04/07/56/25/360_F_407562548_JxUfwmEJBDVpJ1ZquXOPvaYWhnQqwOW6.jpg",
        "https://t3.ftcdn.net/jpg/00/77/71/12/360_F_77711294_BA5QTjtgGPmLKCXGdtbAgZciL4kEwCnx.jpg",
        "https://t4.ftcdn.net/jpg/04/07/56/25/360_F_407562548_JxUfwmEJBDVpJ1ZquXOPvaYWhnQqwOW6.jpg",
        "https://thumbs.dreamstime.com/b/male-student-smiling-portrait-young-man-34441489.jpg",
        "https://d39l2hkdp2esp1.cloudfront.net/img/photo/128391/128391_00_2x.jpg?20170717010025",
        "https://media.istockphoto.com/id/138017387/photo/asian-college-student.jpg?s=612x612&w=0&k=20&c=2UDa5P72h-2TbvhJ5btBRpLw1lxr81t9n-ISCJFwaLs=",
        "https://as2.ftcdn.net/v2/jpg/01/48/13/17/1000_F_148131790_dkm5dYPZeg18QZh3RLDYADpAhMkx6rZZ.jpg",
        "https://st2.depositphotos.com/4431055/11862/i/950/depositphotos_118621692-stock-photo-young-female-college-student.jpg",
        "https://jacoblund.com/cdn/shop/products/07c907b90753c50f8fca65d658ff20af.jpg?v=1679492747",
        "https://dm0qx8t0i9gc9.cloudfront.net/watermarks/image/rDtN98Qoishumwih/female-college-student-on-campus_Bthbb6aRri_SB_PM.jpg",
        "https://t3.ftcdn.net/jpg/05/60/00/24/360_F_560002450_oxu1G9y76P4vVPNugw0KMOrYi954v6XL.jpg",
        "https://t3.ftcdn.net/jpg/02/16/19/32/360_F_216193252_CVgbuEtqoDuMISiRkdpfdRJlcVHsrmft.jpg",
        "https://media.gettyimages.com/id/1438969575/photo/smiling-young-male-college-student-wearing-headphones-standing-in-a-classroom.jpg?s=612x612&w=gi&k=20&c=SpIONFFVzrC2OpgxeC2GEpUs0mDQxjw8xn9Z-gfGs5c=",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwNbH4zFWSR1XZrZtbVb9MbT6GG0gBeCB3rA&usqp=CAU",
        "https://c8.alamy.com/comp/2H5B501/male-student-studying-in-university-library-using-laptop-having-video-call-2H5B501.jpg",
        "https://i.pinimg.com/736x/ba/7c/b6/ba7cb679f31fe2d7ebfd3de27d9a76e7.jpg",
        "https://st2.depositphotos.com/4431055/11856/i/950/depositphotos_118562150-stock-photo-young-student-girl.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyQuVykzGxSOipHdHGK6UXn2pIrX_ixRgjGMRG-NuKTHTWIH1sHvx4g5rB1LTh0LFGnBU&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT87EJ7Mi1JbfHVYYrGfLZMFChbaMoMWYGNXUJkzfgm6g&s",
        "https://d39l2hkdp2esp1.cloudfront.net/img/photo/167501/167501_00_2x.jpg?20190315055553",
        "https://previews.123rf.com/images/olegdudko/olegdudko1507/olegdudko150708112/42302896-university-student-college-student.jpg",
        "https://media.istockphoto.com/id/1473893101/photo/cheerful-young-arab-student-female-listening-music-with-smartphone-and-earphones-outdoors.webp?b=1&s=170667a&w=0&k=20&c=YNehy14FpW3SSTblPK4MNR6xgZpPTKWSEWgKYeEmG-Q=",
        "https://media.gettyimages.com/id/1439945611/photo/student-writing-in-notebook-while-sitting-with-tablet-pc-in-college-library.jpg?s=612x612&w=gi&k=20&c=EYz0Q2_Nye8e0AuN4d-uXjHVjqg6rma7P2hufD7Kv4Y=",
        "https://as2.ftcdn.net/v2/jpg/01/82/04/15/1000_F_182041578_lONY3gqsIz5uGveQfl0tdcUF0HXG4r7f.jpg",
        "https://as1.ftcdn.net/v2/jpg/00/62/34/64/1000_F_62346444_aYse1pamJOSy9M0NHrQ8RcdMtX4WgIV6.jpg",
        "https://media.istockphoto.com/id/1288634246/photo/young-latin-student-girl-smiling-happy-holding-folder-at-the-city.jpg?s=612x612&w=0&k=20&c=SSR1Z7eLlLBges4kLzzXrBP5glsz5ZpiSlmJt3wU9AI=",
        "https://static.vecteezy.com/system/resources/previews/006/855/780/non_2x/indian-student-with-books-and-bag-at-college-campus-photo.jpg",
        "https://media.istockphoto.com/id/143071480/photo/student-standing-on-steps-outdoors.jpg?s=612x612&w=0&k=20&c=A7TPrLH_am1xvXB-c-3zqEFDuJr_UflG50l95BosTnI=",
        "https://media.gettyimages.com/id/1340306546/photo/college-student-on-campus.jpg?s=612x612&w=gi&k=20&c=HhugQK3FgygofyFswDtwQGZDGd6JQZRwZEAhOpde2xg=",
        "https://media.gettyimages.com/id/673855030/photo/portrait-young-woman-student.jpg?s=612x612&w=gi&k=20&c=upVMf3kR41gMI1TYk-rsSb2Xq3WkPp27vL9wuV2jfHk=",
        "https://media.gettyimages.com/id/481292759/photo/portrait-of-young-architect.jpg?s=612x612&w=gi&k=20&c=lP4cAT846f81KQkbHCUGbClDNQ0kPDR6LWeWSoBQYgE=",
        "https://media.gettyimages.com/id/1438969575/photo/smiling-young-male-college-student-wearing-headphones-standing-in-a-classroom.jpg?s=612x612&w=gi&k=20&c=SpIONFFVzrC2OpgxeC2GEpUs0mDQxjw8xn9Z-gfGs5c=",
        "https://previews.123rf.com/images/stockbroker/stockbroker1702/stockbroker170200732/71304915-young-adult-male-student-in-the-lobby-of-a-university.jpg",
        "https://media.istockphoto.com/id/1384332904/photo/laughing-young-man.jpg?s=612x612&w=0&k=20&c=FsGVyzNwhKoZMLoVTUm87Y-RMunRciRjHxn_OKH9nWw=",
        "https://as2.ftcdn.net/v2/jpg/02/17/92/97/1000_F_217929728_63fmjOvGxq6k8AhAbaBrby8Le7ZgdzIZ.jpg",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwrEXAK_0vi_pqZ9PGH8ZSuqpI1J2Ut2c33Dnzdwy8pQ&s",
        "https://media.istockphoto.com/id/1392990621/photo/smart-handsome-positive-indian-or-arabian-guy-with-glasses-in-casual-wear-student-or.jpg?s=612x612&w=0&k=20&c=qyj5Dh8_uN5Xue9aICOI0z_OYyzNh_f1pFeAhRA4FQA=",
        "https://static.vecteezy.com/system/resources/previews/007/732/712/non_2x/portrait-of-young-adult-asian-college-student-woman-with-notebook-on-day-in-the-city-photo.jpg",
        "https://media.istockphoto.com/id/1325565779/photo/smiling-african-american-business-woman-wearing-stylish-eyeglasses-looking-at-camera-standing.jpg?s=612x612&w=0&k=20&c=wsNA_POOFtsKGjucqci4ndeSX-NWcT3hEt9E3a_oXpY=",
        "https://media.istockphoto.com/id/1368424494/photo/studio-portrait-of-a-cheerful-woman.jpg?s=612x612&w=0&k=20&c=ISNDV3ZXeNU6VvDhR7KXFd6y0saq4Eji15cep_Gj8Eg="
    ]

hobby_options = [
    "Art",  
    "Badminton",
    "Baking", 
    "Baseball", 
    "Basketball",
    "Bars",
    "Board games/card games", 
    "Bowling", 
    "Boxing",
    "Cars", 
    "Concerts",
    "Cooking", 
    "Crafts", 
    "Crew", 
    "Cycling", 
    "Dancing", 
    "Design", 
    "Fishing", 
    "Football", 
    "Gaming", 
    "Go karting", 
    "Golf", 
    "Gym", 
    "Gymnastics", 
    "Hiking",
    "Hockey", 
    "Karaoke",
    "Knitting",
    "Make-up", 
    "Making videos", 
    "MMA", 
    "Photography", 
    "Pilates", 
    "Ping pong",
    "Playing instruments",
    "Reading",
    "Rock Climbing", 
    "Running", 
    "Rugby", 
    "Singing",
    "Sports", 
    "Skateboarding", 
    "Skiing", 
    "Snowboarding", 
    "Surfing", 
    "Swimming", 
    "Tennis",
    "Traveling", 
    "Volleyball", 
    "Writing",
    "Yoga"
]


categories_and_questions = {
        "Required Questions": [
            # {"text": "What is your first and last name", "type": "text_input"},
            # {"text": "Tell us your birthday date", "type": "text_input"},
            # {"text": "What's your major?", "type": "multiple choice", "options": major_options},
            # {"text": "How do you identify yourself?", "type": "multiple choice", "options": ["Female", "Male", "Non-binary"]},
            # {"text": "Tell us more about yourself", "type": "text_input"},
            {"text": "What is your budget for housing?", "type": "multiple choice", "options": ['$300 or less', "$300 - $500", "$500 - $700", "$700 - $900", "$1000 or more"]},
            {"text": "Will you bring a pet? If so, what kind of pet?", "type": "multiple choice", "options": ["No pets", "Dog", "Cat", "Fish", "bird"]},
            {"text": "Are you open to living with pets?", "type": "multiple choice", "options": ["Yes", "No", "No preference"]},
            {"text": "Do you smoke inside or outside?", "type": "multiple choice", "options": ["I don't smoke", "Inside", "Outside"]}
        ],

        "Personality / Hobbies": [
            {"text": "What's your personality type?", "type": "multiple choice", "options": ["Introvert", "Ambivert", "Extrovert"]},
            {"text": "What are your hobbies/interests? (Select All that Apply)", "type": "multi select", "options": hobby_options}
        ],
        "Cleanliness": [
            {"text": "How would you rate your cleanliness?", "type": "multiple choice", "options": ["Very organized", "Disorganized/Messy", "Dirty"]},
            {"text": "What would you want your roommate's cleanliness to be?", "type": "multiple choice", "options": ["Very organized", "Disorganized/Messy", "Dirty"]},
            {"text": "Shared chores or individual chores?", "type": "multiple choice", "options": ["Shared", "Individual"]}
        ],
        "Sleep Habits": [
            {"text": "What time do you normally go to sleep?", "type": "multiple choice", "options": ["8pm - 10pm", "10pm - 12am", "1am or later"]},
            {"text": "What time do you normally wake up?", "type": "multiple choice", "options": ["5am - 7am", "8am - 10am", "11am or later"]},
            {"text": "Are you a light or heavy sleeper?", "type": "multiple choice", "options": ["light", "heavy", "neither"]}
        ],
        "Temperature": [
            {"text": "What temperature would you like the house/apartment to be?", "type": "multiple choice", "options": ["65F or less", "65F-73F", "73F or more" ]}
        ],
        "Cooking": [
            {"text": "How often do you cook?", "type":"multiple choice", "options": ["never", "sometimes", "often"]},
            {"text": "Do you have any food allergies or dietary restrictions that may be impacted by a roommate? If so, what are they? (Select All that Apply)", "type": "multi select", "options": ["milk", "eggs", "fish", "pork", "crustacean shellfish", "peanuts", "wheat", "soybeans", "treenut", "other"]}
        ],
        
        "Housing Preferences": [
            {"text": "How close to campus would you like to live?", "type": "multiple choice", "options": ["Walking distance (5min - 15 min)", "Around 10 min drive", "15 min drive or more","No preference"]},
            {"text": "Would you like a shared or private room?", "type": "multiple choice", "options": ["Shared", "Private", "No preference"]},
            {"text": "Would you like a private bathroom?", "type": "multiple choice", "options": ["Yes", "No", "No preference"]},
            {"text": "Would you want to have in-unit laundry?", "type": "multiple choice", "options": ["Yes", "No", "No preference"]},
            {"text": "What amenities would you like to have? (Select All that Apply)", "type": "multi select", "options": ["Gym", "Pool", "Dog park", "No preference"]}
        ],
        "Social Life": [
            {"text": "How often do you have guests", "type": "multiple choice", "options": ["Often", "Sometimes", "Never"]},
            {"text": "Would you like to host parties at your apartment?", "type": "multiple choice", "options": ["Yes", "No", "Maybe"]},
            {"text": "How noisy would you say you are?", "type": "multiple choice", "options": ["Noisy", "Quiet", "Normal"]}
        ]
}

age_similarity_weight = .1
bio_similarity_weight = .15
major_similarity_weight = .05
gender_similarity_weight = .45
answer_similarity_weight = .25